### ISSUE TITLE
Feature request: add description option for variables

### ISSUE THREAD

**Issue by ednxzu** [exaluc/docsible#21]
**Is your feature request related to a problem? Please describe.**
currently you can append `# title: <title>` and `# required: <bool>` to each variable

it would be nice to be nice to be able to provide a `# description: <some_text>` aswell in order to provide some explaination as to how the variable should be used/populated for more complex ones.

**Describe the solution you'd like**
parse an additional `# description:` entry for each variable.

this possibly break the nicely formatted table that's currently used to display all variables because a description might need to include markdown in itself like examples etc... ? 

### variable_name
 - Title: <title>
 - Required: <bool>
 - Description: <descritpion>

might be a nicer way to format it, but I don't really have an opinion.

**Describe alternatives you've considered**
use the currently provided title and required fields, but this breaks the table if large decriptions are added 

**Additional context**
currently working on some somewhat complicated roles for deploying distributed stuff, variables are not obvious to populate if you don't have examples. I was doing it manually but your tool is way cooler, and I can generate README in CI which saves me a ton of time ! thank you !

**Comment by exaluc** [comment]
Hello @ednxzu
This can be done, yes.
I dunno yet how to place it on the table the description.
If description is to long this will break the view for those who dont got any description.

**Comment by exaluc** [comment]
You can install with upgrade from this branch and try with command:
```python
pip install git+https://github.com/exaluc/docsible.git@feature/description_for_vars#egg=docsible
```
Merging after tests on all my roles.

**Comment by ednxzu** [comment]
This looks good ! I like the folding section making the readme still short.

2 notes:
 - description isnt rendered in markdown (see https://github.com/ednz-cloud/hashicorp_consul/blob/feat/hashistack-integration/README.md). This is minor and can be improved later probbly.
 - docsible does not add a new empty line at the end of the readme (also minor, but fails pre-commit hooks in my case)

Otherwise, I like it ! thank you !

**Comment by exaluc** [comment]
Multiline and jinja2 tpl where never supported.
Try the new push, I've added to handle multi line. Value is not showed just a tag <multiline value>
