### ISSUE TITLE
[BUG] array of variables

### ISSUE THREAD

**Issue by louju14** [exaluc/docsible#6]
## Describe the Bug

The single variables are OK, but if we have an array of variables it's not working properly
## Environment

- **Docsible Version**: 0.5.8
- **Python Version**: 3.11
- **Operating System**: Linux
- **CLI or Script**: CLI command in CI/CD gitlab

## To Reproduce

here my variables : 

fm_hardening_sshd_login_grace_time: true
fm_hardening_openssh_default_policy: true

packages_ssh:
  - openssh
  - openssh-server
  - openssh-clients
  - rpmdevtools

## Expected Behavior

Array of variables
packages_ssh | openssh ; openssh-server ; openssh-clients ; rpmdevtools

## Actual Behavior

nothing...

## extra question

Can we have an explanation on how customize or create template to generate a customized README.md file ?

**Comment by exaluc** [comment]
@louju14 this one will be a future feature. I'll open one.

"Can we have an explanation on how customize or create template to generate a customized README.md file ?"
